In [1]:
import numpy as np

In [5]:
l = [1,2,3,4,5,6]
print(l)
l = np.array(l,dtype = np.int8)
l

[1, 2, 3, 4, 5, 6]


array([1, 2, 3, 4, 5, 6], dtype=int8)

In [6]:
l.dtype

dtype('int8')

In [7]:
l1 = [1,2,3,4,5.5,6]
l1 = np.array(l1)
l1

array([1. , 2. , 3. , 4. , 5.5, 6. ])

In [8]:
l2 = [1,2,3,'4',5.5,6]
l2 = np.array(l2)
l2

array(['1', '2', '3', '4', '5.5', '6'], dtype='<U32')

In [10]:
l3 = np.arange(1,11,2)
l3

array([1, 3, 5, 7, 9])

In [12]:
l3 = np.linspace(1,5,20)
l3

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [19]:
l4 = np.random.rand(3,5)
l4

array([[0.97498623, 0.87644546, 0.4480338 , 0.37297574, 0.67628393],
       [0.98729754, 0.99791731, 0.56070464, 0.82330929, 0.16458042],
       [0.21794939, 0.73293442, 0.15453929, 0.16152944, 0.51970734]])

In [17]:
l5 = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
l5 = np.array(l5)
l5

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
l5.shape

(4, 3)

In [20]:
l5.ndim

2

In [30]:
d_arr = np.full((3,2,4,5),3.2)
d_arr

array([[[[3.2, 3.2, 3.2, 3.2, 3.2],
         [3.2, 3.2, 3.2, 3.2, 3.2],
         [3.2, 3.2, 3.2, 3.2, 3.2],
         [3.2, 3.2, 3.2, 3.2, 3.2]],

        [[3.2, 3.2, 3.2, 3.2, 3.2],
         [3.2, 3.2, 3.2, 3.2, 3.2],
         [3.2, 3.2, 3.2, 3.2, 3.2],
         [3.2, 3.2, 3.2, 3.2, 3.2]]],


       [[[3.2, 3.2, 3.2, 3.2, 3.2],
         [3.2, 3.2, 3.2, 3.2, 3.2],
         [3.2, 3.2, 3.2, 3.2, 3.2],
         [3.2, 3.2, 3.2, 3.2, 3.2]],

        [[3.2, 3.2, 3.2, 3.2, 3.2],
         [3.2, 3.2, 3.2, 3.2, 3.2],
         [3.2, 3.2, 3.2, 3.2, 3.2],
         [3.2, 3.2, 3.2, 3.2, 3.2]]],


       [[[3.2, 3.2, 3.2, 3.2, 3.2],
         [3.2, 3.2, 3.2, 3.2, 3.2],
         [3.2, 3.2, 3.2, 3.2, 3.2],
         [3.2, 3.2, 3.2, 3.2, 3.2]],

        [[3.2, 3.2, 3.2, 3.2, 3.2],
         [3.2, 3.2, 3.2, 3.2, 3.2],
         [3.2, 3.2, 3.2, 3.2, 3.2],
         [3.2, 3.2, 3.2, 3.2, 3.2]]]])

In [25]:
d_arr.ndim

3

In [32]:
mat = np.linspace(20,50,24).reshape(3,4,2)
mat

array([[[20.        , 21.30434783],
        [22.60869565, 23.91304348],
        [25.2173913 , 26.52173913],
        [27.82608696, 29.13043478]],

       [[30.43478261, 31.73913043],
        [33.04347826, 34.34782609],
        [35.65217391, 36.95652174],
        [38.26086957, 39.56521739]],

       [[40.86956522, 42.17391304],
        [43.47826087, 44.7826087 ],
        [46.08695652, 47.39130435],
        [48.69565217, 50.        ]]])