In [2]:
import numpy as np

In [4]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
a.shape

(3, 3)

In [9]:
a.size

9

In [10]:
a.dtype

dtype('int64')

In [11]:
a.itemsize

8

In [14]:
b = np.arange(1,25,1)
b.size

24

In [25]:
b = b.reshape(6,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [26]:
b[1,1]

6

In [38]:
b[2:5,1:3] = [20,200]
b

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  20, 200,  12],
       [ 13,  20, 200,  16],
       [ 17,  20, 200,  20],
       [ 21,  22,  23,  24]])

In [40]:
b[1,1:3]= [30,35]
b

array([[  1,   2,   3,   4],
       [  5,  30,  35,   8],
       [  9,  20, 200,  12],
       [ 13,  20, 200,  16],
       [ 17,  20, 200,  20],
       [ 21,  22,  23,  24]])

In [32]:
b[2:5:2,1:4:2]

array([[10, 12],
       [18, 20]])

In [34]:
b[::-1,::-1]

array([[24, 23, 22, 21],
       [20, 19, 18, 17],
       [16, 15, 14, 13],
       [12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [24]:
# b.reshape(4,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [23]:
# b.reshape(4,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [44]:
c= b[1:3,2:5].copy()
c[:,:] = 300
c

array([[300, 300],
       [300, 300]])

In [45]:
b

array([[  1,   2,   3,   4],
       [  5,  30,  35,   8],
       [  9,  20, 200,  12],
       [ 13,  20, 200,  16],
       [ 17,  20, 200,  20],
       [ 21,  22,  23,  24]])

In [46]:
b[[True,True,False,True,False,False]]

array([[  1,   2,   3,   4],
       [  5,  30,  35,   8],
       [ 13,  20, 200,  16]])

# Linear algebra with numpy

In [49]:
'''
2x-3y = 8
-5x+8y = 0
'''

'\n2x-3y = 8\n-5x+8y = 0\n'

In [54]:
var = np.array([[2,-3],[-5,8]])
dep_var = [8,0]
sol = np.linalg.solve(var,dep_var)

In [55]:
var

array([[ 2, -3],
       [-5,  8]])

In [52]:
sol

array([64., 40.])

In [56]:
def multiply_loops(A, B):
    C = np.zeros((A.shape[0], B.shape[1]))
    for i in range(A.shape[1]):
        for j in range(B.shape[0]):
            C[i, j] = A[i, j] * B[j, i]
    return C

In [77]:
a = np.random.rand(100,100)
b = np.random.rand(100,100)

In [78]:
import time

In [79]:
start = time.time()
print(multiply_loops(a,b))
stop = time.time()
print('time taken = ', stop -start)

[[9.06851502e-02 5.85451313e-01 3.74147162e-01 ... 8.17160060e-02
  1.93299685e-01 9.22742507e-03]
 [1.06062858e-01 1.59886931e-03 1.95637924e-01 ... 5.81725382e-05
  4.29949973e-01 4.50631050e-02]
 [7.31842218e-02 3.24665229e-02 4.94160947e-02 ... 3.10895831e-01
  4.43206364e-02 3.39006497e-01]
 ...
 [1.90181526e-01 2.99578208e-01 1.56410877e-02 ... 4.01128300e-01
  4.47795823e-01 6.34894970e-02]
 [4.92679325e-01 9.92811678e-02 1.69686759e-01 ... 7.02719598e-01
  1.06631231e-01 2.76575632e-01]
 [4.87345331e-03 5.41782678e-01 1.03423627e-01 ... 4.81871073e-01
  1.69815893e-01 2.25812434e-01]]
time taken =  0.006612300872802734


In [80]:
start = time.time()
print(a@b)
stop = time.time()
print('time taken = ', stop - start)

[[26.92278072 22.82928277 25.88398021 ... 24.44536251 25.32912713
  26.32089373]
 [26.75206689 25.50293094 27.17217539 ... 27.69008429 28.00876128
  26.09810052]
 [26.57856941 22.45915501 24.6235446  ... 25.14951436 25.02499509
  24.70575639]
 ...
 [27.80270715 25.18504617 27.04607768 ... 25.30568881 26.34383884
  27.65413092]
 [24.54028343 21.61035822 23.40095246 ... 24.4904203  26.10349027
  23.52951017]
 [25.12210204 23.22062225 26.37318921 ... 26.01447832 25.95272565
  24.41350615]]
time taken =  0.0026857852935791016
