In [1]:
10-2

8

In [6]:
import numpy as np
print('numpy imported')

numpy imported


In [7]:
# Numpy works on arrays: array is a collection of similar type of elements

In [9]:
l = [1.2,3,6,]
l_arr = np.array(l)
l_arr

array([1.2, 3. , 6. ])

In [10]:
l1 = [1,2,3,4,5,'6']
l1_arr = np.array(l1)
l1_arr

array(['1', '2', '3', '4', '5', '6'], dtype='<U21')

In [11]:
l1_arr.dtype

dtype('<U21')

In [12]:
l_arr.dtype

dtype('float64')

In [13]:
x = [z for z in range(1,11)]
y = np.array(x)
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
# arange function

In [15]:
v = np.arange(1,11)
v

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])