In [1]:
import numpy as np

In [32]:
arr = np.array([1])
type(arr)

numpy.ndarray

In [33]:
arr.__sizeof__()

112

In [34]:
arr.dtype

dtype('int64')

In [43]:
l = [[1,2,3],[4,5,6,]]
arr_1 = np.array(l)
arr_1

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
arr_1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
arr_1.ndim

2

In [44]:
arr_1.shape

(2, 3)

In [45]:
arr_1.size

6

In [57]:
a = np.arange(0,10,3)
a

array([0, 3, 6, 9])

In [58]:
len(a)

4

In [61]:
b = np.random.rand(10,10)
b

array([[0.02371295, 0.32779278, 0.26349468, 0.52379759, 0.29563828,
        0.21461809, 0.56290315, 0.22871657, 0.78727392, 0.82576186],
       [0.23661403, 0.42137084, 0.38293445, 0.3837126 , 0.67317362,
        0.39138853, 0.30597727, 0.86946587, 0.27568179, 0.60043128],
       [0.04935185, 0.384061  , 0.18003925, 0.33478019, 0.95371324,
        0.62638191, 0.65169219, 0.67309322, 0.75514084, 0.88085564],
       [0.17746157, 0.97475723, 0.46317388, 0.40704339, 0.22524388,
        0.82279656, 0.6587661 , 0.60472988, 0.81350594, 0.51608561],
       [0.18740521, 0.13824341, 0.38781449, 0.20258642, 0.8101014 ,
        0.71839125, 0.7908676 , 0.75371129, 0.65907413, 0.38486501],
       [0.72115415, 0.73835028, 0.50473789, 0.92962002, 0.12702847,
        0.68976511, 0.08461377, 0.06937715, 0.35730705, 0.28121406],
       [0.9565577 , 0.64612647, 0.56790137, 0.07499117, 0.91761465,
        0.52170462, 0.82792131, 0.43648987, 0.59495039, 0.25310994],
       [0.68376298, 0.19901532, 0.6516478

In [62]:
b[4,2]

0.3878144857445732

In [63]:
b[4:9,2:6]

array([[0.38781449, 0.20258642, 0.8101014 , 0.71839125],
       [0.50473789, 0.92962002, 0.12702847, 0.68976511],
       [0.56790137, 0.07499117, 0.91761465, 0.52170462],
       [0.65164789, 0.34503362, 0.43517341, 0.94376317],
       [0.96178038, 0.07275853, 0.06132494, 0.40599229]])