In [2]:
import numpy as np

In [3]:
a = np.random.rand(2,3)
a

array([[0.15084572, 0.97599289, 0.59599358],
       [0.38757359, 0.98579011, 0.7525032 ]])

In [26]:
d_3 = np.random.rand(2,3,5)
d_3

array([[[0.62911702, 0.93566533, 0.29639402, 0.24132766, 0.4769698 ],
        [0.87755611, 0.06080829, 0.79431127, 0.82067195, 0.74102873],
        [0.89375748, 0.17663945, 0.83480842, 0.39304356, 0.21762551]],

       [[0.43125525, 0.36799761, 0.41008851, 0.93449441, 0.36070683],
        [0.31665363, 0.69665391, 0.58644896, 0.31918291, 0.34308628],
        [0.30580908, 0.06670157, 0.46638387, 0.18495113, 0.95160282]]])

In [27]:
d_3.shape

(2, 3, 5)

In [28]:
d_3.itemsize

8

In [29]:
b = np.arange(0,2,0.5)
b

array([0. , 0.5, 1. , 1.5])

In [30]:
d_3 = d_3.reshape(6,5)

In [43]:
d_3

array([[0.62911702, 0.93566533, 0.29639402, 0.24132766, 0.4769698 ],
       [0.87755611, 0.06080829, 0.79431127, 0.82067195, 0.74102873],
       [0.89375748, 0.17663945, 0.83480842, 0.39304356, 0.21762551],
       [0.43125525, 0.36799761, 0.41008851, 0.93449441, 0.36070683],
       [0.31665363, 0.69665391, 0.58644896, 0.31918291, 0.34308628],
       [0.30580908, 0.06670157, 0.46638387, 0.18495113, 0.95160282]])

In [35]:
d_3[1,1]

0.06080828518201431

In [45]:
x = d_3[1:4,1:4].copy()

In [46]:
d_3[1:4,1:4] = x

In [55]:
x[:,:]

array([[0.06080829, 0.79431127, 0.82067195],
       [0.17663945, 0.83480842, 0.39304356],
       [0.36799761, 0.41008851, 0.93449441]])

In [63]:
x = x.ravel()

In [64]:
x.shape

(9,)

In [65]:
boole = np.array([True,False,True,True,False,True,True,False,True])

In [66]:
x[boole]

array([0.06080829, 0.82067195, 0.17663945, 0.39304356, 0.36799761,
       0.93449441])