In [1]:
import numpy as np

In [23]:
x = np.random.rand(2,2)
y = np.random.rand(3,3)

In [24]:
x

array([[0.12836105, 0.12763669],
       [0.93888993, 0.64235653]])

In [25]:
y

array([[0.77183007, 0.77922107, 0.81812898],
       [0.50801915, 0.30478598, 0.12240177],
       [0.83281886, 0.37006406, 0.68866764]])

In [26]:
x_,y_ =np.meshgrid(x,y)

In [27]:
x_

array([[0.12836105, 0.12763669, 0.93888993, 0.64235653],
       [0.12836105, 0.12763669, 0.93888993, 0.64235653],
       [0.12836105, 0.12763669, 0.93888993, 0.64235653],
       [0.12836105, 0.12763669, 0.93888993, 0.64235653],
       [0.12836105, 0.12763669, 0.93888993, 0.64235653],
       [0.12836105, 0.12763669, 0.93888993, 0.64235653],
       [0.12836105, 0.12763669, 0.93888993, 0.64235653],
       [0.12836105, 0.12763669, 0.93888993, 0.64235653],
       [0.12836105, 0.12763669, 0.93888993, 0.64235653]])

In [30]:
y_

array([[0.77183007, 0.77183007, 0.77183007, 0.77183007],
       [0.77922107, 0.77922107, 0.77922107, 0.77922107],
       [0.81812898, 0.81812898, 0.81812898, 0.81812898],
       [0.50801915, 0.50801915, 0.50801915, 0.50801915],
       [0.30478598, 0.30478598, 0.30478598, 0.30478598],
       [0.12240177, 0.12240177, 0.12240177, 0.12240177],
       [0.83281886, 0.83281886, 0.83281886, 0.83281886],
       [0.37006406, 0.37006406, 0.37006406, 0.37006406],
       [0.68866764, 0.68866764, 0.68866764, 0.68866764]])

In [28]:
x_.shape

(9, 4)

In [29]:
y_.shape

(9, 4)

In [48]:
arr = np.array([1,2,3,4,5,6,7,8])

In [49]:
arr.shape

(8,)

In [52]:
arr = arr.reshape(4,2)

In [53]:
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [54]:
arr= arr.reshape(8,1)
arr

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [55]:
arr = np.c_[arr,arr,arr,arr]

In [56]:
arr5

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7],
       [8, 8, 8, 8]])