In [1]:
import numpy as np

In [4]:
a = np.random.rand(10,5)
a

array([[0.67996179, 0.64133274, 0.75701097, 0.66868773, 0.31131097],
       [0.78394214, 0.71816103, 0.29523273, 0.05872054, 0.66179268],
       [0.26663433, 0.16796405, 0.0168084 , 0.90125861, 0.96911128],
       [0.0117164 , 0.97212533, 0.95135837, 0.03524171, 0.96892202],
       [0.11021472, 0.39493412, 0.00254439, 0.62940335, 0.33655603],
       [0.64522545, 0.95223474, 0.70065954, 0.16069837, 0.65951987],
       [0.62874419, 0.54143669, 0.49433441, 0.14504931, 0.78924571],
       [0.33733374, 0.25982261, 0.80476477, 0.10425177, 0.77755566],
       [0.94789201, 0.79107319, 0.52233763, 0.06510057, 0.53198783],
       [0.94591363, 0.69770952, 0.05570618, 0.46309615, 0.98466364]])

In [6]:
a[4,3]

0.6294033451666898

In [8]:
a[3:7,1:4] = np.nan

In [9]:
a

array([[0.67996179, 0.64133274, 0.75701097, 0.66868773, 0.31131097],
       [0.78394214, 0.71816103, 0.29523273, 0.05872054, 0.66179268],
       [0.26663433, 0.16796405, 0.0168084 , 0.90125861, 0.96911128],
       [0.0117164 ,        nan,        nan,        nan, 0.96892202],
       [0.11021472,        nan,        nan,        nan, 0.33655603],
       [0.64522545,        nan,        nan,        nan, 0.65951987],
       [0.62874419,        nan,        nan,        nan, 0.78924571],
       [0.33733374, 0.25982261, 0.80476477, 0.10425177, 0.77755566],
       [0.94789201, 0.79107319, 0.52233763, 0.06510057, 0.53198783],
       [0.94591363, 0.69770952, 0.05570618, 0.46309615, 0.98466364]])

In [16]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
a.mean()

4.5

In [18]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [22]:
a.sum(axis = 0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [25]:
a = a.reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [26]:
a.T

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])