In [1]:
import numpy as np
np.__version__

'1.20.2'

In [8]:
print('hello')

hello


In [7]:
import matplotlib.pyplot as plt

In [3]:
X = np.random.randint(1,100,(1000,1000))
X.shape

(1000, 1000)

In [24]:
Y = np.random.randint(1,100,(1000,1000))

In [25]:
from time import time

In [ ]:
# Matrix Multiplication using for loop

In [30]:
start = time()
result = np.zeros((1000,1000))
for i in range(len(X)):
   # iterate through columns of Y
   for j in range(len(Y[0])):
       # iterate through rows of Y
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]
stop = time.time()
for r in result:
   print(r)
print('total time take is:',stop - start)

KeyboardInterrupt: 

# Matrix DOT Multiplication using Numpy

In [33]:
start = time()
res = X.dot(Y)
stop = time()
print('total time take is:',stop - start)

total time take is: 1.816565752029419


# Matrix Cross Multiplication Using Numpy

In [50]:
start = time()
cross_res = X @ Y
stop = time()
print('total time take is:',stop - start)


total time take is: 1.8765449523925781


array([2542001, 2497500, 2523941, 2517932, 2505374])

In [59]:
cross_res

array([[2437429, 2551868, 2483789, ..., 2426998, 2474337, 2450553],
       [2498804, 2527007, 2452422, ..., 2448427, 2537925, 2539620],
       [2578883, 2601134, 2559073, ..., 2532183, 2552909, 2553190],
       ...,
       [2521161, 2558137, 2491511, ..., 2441774, 2470637, 2476175],
       [2555042, 2592672, 2544845, ..., 2550045, 2453037, 2523855],
       [2395240, 2501960, 2434176, ..., 2404049, 2471044, 2400829]])

In [60]:
cross_res[0,2]

2483789

In [43]:
np.random.rand()

0.18612402265232653

In [47]:
np.random.rand(5,2)

array([[0.7671746 , 0.59061099],
       [0.40218883, 0.45507691],
       [0.46402091, 0.41426902],
       [0.25626801, 0.05205488],
       [0.66407712, 0.14262638]])

In [70]:
import sys

In [4]:
a = np.array([1,2,3,4,5],dtype = np.int8)

In [5]:
sys.getsizeof(a)

109

In [6]:
b = [1,2,3,4,5]

In [7]:
sys.getsizeof(b)

120

SyntaxError: invalid syntax (<ipython-input-8-df0eca0bfa5c>, line 1)

In [16]:
b = np.array(b, dtype=np.float16)
sys.getsizeof(b)

114

In [152]:
tup =((1,2,3,4,5,6),(7,8,9,10,11,12))
tup

((1, 2, 3, 4, 5, 6), (7, 8, 9, 10, 11, 12))

In [153]:
tup = np.array(tup)
type(tup)

numpy.ndarray

In [154]:
tup.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [155]:
tup = tup.ravel()
tup[::-1]

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [156]:
tup.reshape(-1,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [157]:
tup.size

12