# NUMPY

In [2]:
import numpy as np

In [3]:
l = [1,2,3,5,4,6.0]
a = np.array(l)
a

array([1., 2., 3., 5., 4., 6.])

In [20]:
l1 = ['10','a',3]
b = np.array(l1)
b

array(['10', 'a', '3'], dtype='<U21')

In [21]:
x= b[2]
type(x)

numpy.str_

In [33]:
arr = np.random.rand(10,5)
arr

array([[0.96874518, 0.07298104, 0.12566293, 0.58459113, 0.72641024],
       [0.70900898, 0.24642438, 0.48998044, 0.24103081, 0.14187056],
       [0.38204073, 0.78295248, 0.53362317, 0.1332437 , 0.28200009],
       [0.3439944 , 0.55133172, 0.93524151, 0.05973168, 0.31604373],
       [0.71887335, 0.35354717, 0.35234927, 0.97046719, 0.91150271],
       [0.69218798, 0.26852627, 0.97753095, 0.97893345, 0.13831802],
       [0.93649779, 0.66085112, 0.93911229, 0.71007088, 0.9933045 ],
       [0.33957466, 0.19018784, 0.06415377, 0.94258879, 0.33290697],
       [0.8740118 , 0.84328914, 0.36540701, 0.51442812, 0.69032954],
       [0.43745712, 0.91163544, 0.40182799, 0.53265747, 0.29813845]])

In [34]:
arr.shape

(10, 5)

In [35]:
arr.size

50

In [37]:
arr.dtype

dtype('float64')

In [38]:
arr.ndim            # rank of array

2

In [39]:
arr[1,1]

0.24642437555412433

In [40]:
arr[1:6,2:5] 

array([[0.48998044, 0.24103081, 0.14187056],
       [0.53362317, 0.1332437 , 0.28200009],
       [0.93524151, 0.05973168, 0.31604373],
       [0.35234927, 0.97046719, 0.91150271],
       [0.97753095, 0.97893345, 0.13831802]])

In [41]:
arr.reshape(2,5,5)

array([[[0.96874518, 0.07298104, 0.12566293, 0.58459113, 0.72641024],
        [0.70900898, 0.24642438, 0.48998044, 0.24103081, 0.14187056],
        [0.38204073, 0.78295248, 0.53362317, 0.1332437 , 0.28200009],
        [0.3439944 , 0.55133172, 0.93524151, 0.05973168, 0.31604373],
        [0.71887335, 0.35354717, 0.35234927, 0.97046719, 0.91150271]],

       [[0.69218798, 0.26852627, 0.97753095, 0.97893345, 0.13831802],
        [0.93649779, 0.66085112, 0.93911229, 0.71007088, 0.9933045 ],
        [0.33957466, 0.19018784, 0.06415377, 0.94258879, 0.33290697],
        [0.8740118 , 0.84328914, 0.36540701, 0.51442812, 0.69032954],
        [0.43745712, 0.91163544, 0.40182799, 0.53265747, 0.29813845]]])

In [44]:
arr.reshape(-1,5,5)

array([[[0.96874518, 0.07298104, 0.12566293, 0.58459113, 0.72641024],
        [0.70900898, 0.24642438, 0.48998044, 0.24103081, 0.14187056],
        [0.38204073, 0.78295248, 0.53362317, 0.1332437 , 0.28200009],
        [0.3439944 , 0.55133172, 0.93524151, 0.05973168, 0.31604373],
        [0.71887335, 0.35354717, 0.35234927, 0.97046719, 0.91150271]],

       [[0.69218798, 0.26852627, 0.97753095, 0.97893345, 0.13831802],
        [0.93649779, 0.66085112, 0.93911229, 0.71007088, 0.9933045 ],
        [0.33957466, 0.19018784, 0.06415377, 0.94258879, 0.33290697],
        [0.8740118 , 0.84328914, 0.36540701, 0.51442812, 0.69032954],
        [0.43745712, 0.91163544, 0.40182799, 0.53265747, 0.29813845]]])

In [46]:
arr

array([[0.96874518, 0.07298104, 0.12566293, 0.58459113, 0.72641024],
       [0.70900898, 0.24642438, 0.48998044, 0.24103081, 0.14187056],
       [0.38204073, 0.78295248, 0.53362317, 0.1332437 , 0.28200009],
       [0.3439944 , 0.55133172, 0.93524151, 0.05973168, 0.31604373],
       [0.71887335, 0.35354717, 0.35234927, 0.97046719, 0.91150271],
       [0.69218798, 0.26852627, 0.97753095, 0.97893345, 0.13831802],
       [0.93649779, 0.66085112, 0.93911229, 0.71007088, 0.9933045 ],
       [0.33957466, 0.19018784, 0.06415377, 0.94258879, 0.33290697],
       [0.8740118 , 0.84328914, 0.36540701, 0.51442812, 0.69032954],
       [0.43745712, 0.91163544, 0.40182799, 0.53265747, 0.29813845]])

In [47]:
arr.mean()

0.5393515190166042

In [50]:
arr.std()

0.29925466014982144

In [52]:
arr.var()

0.08955335162138514

In [53]:
(arr.std()**2)

0.08955335162138513

In [54]:
np.sqrt(arr.var())

0.29925466014982144

In [58]:
for i in (arr.mean,arr.sum,arr.std,arr.var,arr.max,arr.min,arr.prod):
    print(f'{i.__name__}    = {i()}')

mean    = 0.5393515190166042
sum    = 26.96757595083021
std    = 0.29925466014982144
var    = 0.08955335162138514
max    = 0.9933044987461694
min    = 0.059731679098740775
prod    = 5.6072899289641225e-19


In [61]:
arr.sum(axis = 0)

array([6.40239199, 4.8817266 , 5.18488933, 5.66774323, 4.83082481])

In [62]:
arr.sum(axis = 1)

array([2.47839053, 1.82831516, 2.11386019, 2.20634304, 3.30673969,
       3.05549667, 4.23983657, 1.86941203, 3.28746561, 2.58171647])

In [63]:
arr.shape

(10, 5)

In [65]:
arr.T.shape

(5, 10)

In [66]:
coeff = [[2,6],[5,3]]
dep = [5,3]
sol = np.linalg.solve(coeff, dep)
sol

array([0.125     , 0.79166667])

In [70]:
m = np.zeros((3,3))
m

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [74]:
m[1:3,1:3]= 20

In [75]:
m

array([[ 0.,  0.,  0.],
       [ 0., 20., 20.],
       [ 0., 20., 20.]])

In [76]:
import pandas as pd

In [78]:
traffic = pd.read_csv('/home/athharv/Downloads/air_traffic_data.csv')
traffic

Activity Period Operating Airline Operating Airline IATA Code  \
0               200507      ATA Airlines                          TZ   
1               200507      ATA Airlines                          TZ   
2               200507      ATA Airlines                          TZ   
3               200507       Air Canada                           AC   
4               200507       Air Canada                           AC   
...                ...               ...                         ...   
15002           201603    Virgin America                          VX   
15003           201603    Virgin America                          VX   
15004           201603    Virgin America                          VX   
15005           201603   Virgin Atlantic                          VS   
15006           201603   Virgin Atlantic                          VS   

      Published Airline Published Airline IATA Code    GEO Summary GEO Region  \
0          ATA Airlines                          TZ       Domestic         US   
1          ATA Airlines                          TZ       Domestic         US   
2          ATA Airlines                          TZ       Domestic         US   
3           Air Canada                           AC  International     Canada   
4           Air Canada                           AC  International     Canada   
...                 ...                         ...            ...        ...   
15002    Virgin America                          VX       Domestic         US   
15003    Virgin America                          VX  International     Mexico   
15004    Virgin America                          VX  International     Mexico   
15005   Virgin Atlantic                          VS  International     Europe   
15006   Virgin Atlantic                          VS  International     Europe   

      Activity Type Code Price Category Code       Terminal Boarding Area  \
0               Deplaned            Low Fare     Terminal 1             B   
1               Enplaned            Low Fare     Terminal 1             B   
2         Thru / Transit            Low Fare     Terminal 1             B   
3               Deplaned               Other     Terminal 1             B   
4               Enplaned               Other     Terminal 1             B   
...                  ...                 ...            ...           ...   
15002           Enplaned            Low Fare     Terminal 2             D   
15003           Deplaned            Low Fare  International             A   
15004           Enplaned            Low Fare     Terminal 2             D   
15005           Deplaned               Other  International             A   
15006           Enplaned               Other  International             A   

       Passenger Count Adjusted Activity Type Code  Adjusted Passenger Count  \
0                27271                    Deplaned                     27271   
1                29131                    Enplaned                     29131   
2                 5415          Thru / Transit * 2                     10830   
3                35156                    Deplaned                     35156   
4                34090                    Enplaned                     34090   
...                ...                         ...                       ...   
15002           194636                    Enplaned                    194636   
15003             4189                    Deplaned                      4189   
15004             4693                    Enplaned                      4693   
15005            12313                    Deplaned                     12313   
15006            10898                    Enplaned                     10898   

       Year  Month  
0      2005   July  
1      2005   July  
2      2005   July  
3      2005   July  
4      2005   July  
...     ...    ...  
15002  2016  March  
15003  2016  March  
15004  2016  March  
15005  2016  March  
15006  2016  March  

[15007 rows x 16 columns]

In [81]:
pd.pivot_table(data = traffic, index = 'Published Airline IATA Code',aggfunc='median')

Activity Period  Adjusted Passenger Count  \
Published Airline IATA Code                                              
4T                                  200606.5                     320.0   
5Y                                  201309.0                      35.5   
9W                                  200809.5                    4264.0   
A8                                  200703.0                       5.0   
AA                                  200910.5                  118358.0   
...                                      ...                       ...   
WN                                  201112.0                  108403.0   
WO                                  200907.0                     259.0   
WS                                  201205.0                    6751.0   
XP                                  200608.0                      73.0   
YX                                  200711.5                    2898.5   

                             Passenger Count    Year  
Published Airline IATA Code                           
4T                                     276.0  2006.0  
5Y                                      34.0  2013.0  
9W                                    4264.0  2008.0  
A8                                       5.0  2007.0  
AA                                  118358.0  2009.0  
...                                      ...     ...  
WN                                  108403.0  2011.0  
WO                                     259.0  2009.0  
WS                                    6751.0  2012.0  
XP                                      73.0  2006.0  
YX                                    2898.5  2007.0  

[64 rows x 4 columns]

In [82]:
x = [1,2,3,5,4,6,9,8,7]
for i,v in enumerate(x):
    print(i,v)

0 1
1 2
2 3
3 5
4 4
5 6
6 9
7 8
8 7


In [83]:
x_ = pd.Series(x)
x_

0    1
1    2
2    3
3    5
4    4
5    6
6    9
7    8
8    7
dtype: int64

In [88]:
z = np.square(x_)
z

0     1
1     4
2     9
3    25
4    16
5    36
6    81
7    64
8    49
dtype: int64

In [89]:
type(z)

pandas.core.series.Series