# Share Price Prediction using RNN

In [55]:
import pandas as pd
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np

In [56]:
sp = pd.read_csv("/mnt/New_Volume/Work_From_Home/Data/SBIN.csv")
sp.head()

Date  series    OPEN   HIGH     LOW   PREV. CLOSE     ltp   close   \
0  01-Apr-21      EQ  367.70  371.9  363.10        364.30  370.95  370.65   
1  05-Apr-21      EQ  367.50  369.2  349.05        370.65  354.00  353.55   
2  06-Apr-21      EQ  355.70  357.0  349.30        353.55  350.95  350.55   
3  07-Apr-21      EQ  351.25  363.2  347.60        350.55  358.20  358.55   
4  08-Apr-21      EQ  361.00  363.3  354.30        358.55  355.95  355.60   

    vwap   52W H   52W L    VOLUME              VALUE   No of trades   
0  367.07   427.7  149.45  31883453  11,703,603,342.10         201211  
1  355.21   427.7  149.45  51743981  18,379,797,141.10         382160  
2  353.10   427.7  149.45  44147709  15,588,499,051.85         273760  
3  358.22   427.7  149.45  48023602  17,203,160,038.90         323113  
4  358.65   427.7  149.45  33370259  11,968,110,091.25         221845

In [57]:
sp.isna().sum()

Date             0
series           0
OPEN             0
HIGH             0
LOW              0
PREV. CLOSE      0
ltp              0
close            0
vwap             0
52W H            0
52W L            0
VOLUME           0
VALUE            0
No of trades     0
dtype: int64

In [58]:
sp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Date           39 non-null     object 
 1   series         39 non-null     object 
 2   OPEN           39 non-null     float64
 3   HIGH           39 non-null     float64
 4   LOW            39 non-null     float64
 5   PREV. CLOSE    39 non-null     float64
 6   ltp            39 non-null     float64
 7   close          39 non-null     float64
 8   vwap           39 non-null     float64
 9   52W H          39 non-null     float64
 10  52W L          39 non-null     float64
 11  VOLUME         39 non-null     int64  
 12  VALUE          39 non-null     object 
 13  No of trades   39 non-null     int64  
dtypes: float64(9), int64(2), object(3)
memory usage: 4.4+ KB


# Target is Closing Price

In [59]:
sp

Date  series    OPEN    HIGH     LOW   PREV. CLOSE     ltp   close   \
0   01-Apr-21      EQ  367.70  371.90  363.10        364.30  370.95  370.65   
1   05-Apr-21      EQ  367.50  369.20  349.05        370.65  354.00  353.55   
2   06-Apr-21      EQ  355.70  357.00  349.30        353.55  350.95  350.55   
3   07-Apr-21      EQ  351.25  363.20  347.60        350.55  358.20  358.55   
4   08-Apr-21      EQ  361.00  363.30  354.30        358.55  355.95  355.60   
5   09-Apr-21      EQ  354.40  364.50  351.20        355.60  352.95  353.00   
6   12-Apr-21      EQ  344.00  344.00  322.55        353.00  330.70  328.85   
7   13-Apr-21      EQ  332.00  342.25  330.50        328.85  341.25  341.00   
8   15-Apr-21      EQ  342.10  347.55  336.10        341.00  342.55  342.70   
9   16-Apr-21      EQ  343.00  345.50  338.65        342.70  339.55  339.90   
10  19-Apr-21      EQ  327.15  332.05  321.30        339.90  330.45  331.15   
11  20-Apr-21      EQ  335.10  339.90  326.70        331.15  329.40  329.50   
12  22-Apr-21      EQ  326.00  337.65  323.30        329.50  336.25  336.65   
13  23-Apr-21      EQ  331.65  339.90  331.65        336.65  335.40  336.45   
14  26-Apr-21      EQ  339.25  347.45  339.25        336.45  344.80  344.30   
15  27-Apr-21      EQ  344.00  354.95  342.40        344.30  354.20  353.05   
16  28-Apr-21      EQ  357.00  364.30  356.05        353.05  362.90  363.40   
17  29-Apr-21      EQ  365.00  369.95  355.50        363.40  357.45  359.40   
18  30-Apr-21      EQ  353.45  362.50  350.45        359.40  352.30  353.50   
19  03-May-21      EQ  349.60  352.50  341.40        353.50  351.45  350.60   
20  04-May-21      EQ  355.00  362.90  350.20        350.60  351.10  351.50   
21  05-May-21      EQ  356.50  357.45  348.00        351.50  356.45  355.40   
22  06-May-21      EQ  358.00  359.35  350.55        355.40  355.85  355.55   
23  07-May-21      EQ  357.50  362.00  353.00        355.55  358.00  358.25   
24  10-May-21      EQ  360.50  367.00  358.80        358.25  362.30  361.70   
25  11-May-21      EQ  356.85  366.40  354.75        361.70  364.10  364.65   
26  12-May-21      EQ  362.80  373.50  361.90        364.65  367.75  367.70   
27  14-May-21      EQ  370.00  372.50  359.55        367.70  360.60  360.45   
28  17-May-21      EQ  364.40  385.20  363.65        360.45  384.45  383.10   
29  18-May-21      EQ  390.00  392.55  380.05        383.10  382.95  382.25   
30  19-May-21      EQ  382.00  389.50  381.20        382.25  384.40  384.40   
31  20-May-21      EQ  387.00  387.80  382.00        384.40  386.80  384.55   
32  21-May-21      EQ  390.00  404.40  378.00        384.55  404.00  401.20   
33  24-May-21      EQ  417.00  419.20  405.30        401.20  411.00  412.05   
34  25-May-21      EQ  415.10  415.50  408.50        412.05  414.10  412.35   
35  26-May-21      EQ  413.80  418.75  410.80        412.35  412.00  413.55   
36  27-May-21      EQ  413.70  429.10  412.00        413.55  426.80  425.20   
37  28-May-21      EQ  430.50  433.65  420.05        425.20  422.00  422.05   
38  31-May-21      EQ  421.00  426.00  418.00        422.05  424.50  424.35   

     vwap   52W H   52W L     VOLUME              VALUE   No of trades   
0   367.07  427.70  149.45   31883453  11,703,603,342.10         201211  
1   355.21  427.70  149.45   51743981  18,379,797,141.10         382160  
2   353.10  427.70  149.45   44147709  15,588,499,051.85         273760  
3   358.22  427.70  149.45   48023602  17,203,160,038.90         323113  
4   358.65  427.70  149.45   33370259  11,968,110,091.25         221845  
5   357.30  427.70  149.45   46473100  16,604,696,682.20         303846  
6   329.89  427.70  149.45   75501713  24,907,319,137.55         579319  
7   336.40  427.70  149.45   49773360  16,743,865,802.60         319183  
8   341.70  427.70  149.45   52992349  18,107,434,663.30         325566  
9   342.01  427.70  149.45   37766793  12,916,560,525.30         237384  
10  326.36  427.70  149.45   5330

In [60]:
sp.columns

Index(['Date ', 'series ', 'OPEN ', 'HIGH ', 'LOW ', 'PREV. CLOSE ', 'ltp ',
       'close ', 'vwap ', '52W H ', '52W L ', 'VOLUME ', 'VALUE ',
       'No of trades '],
      dtype='object')

In [61]:
sp.drop(labels = ['Date ','series ','52W H ', '52W L ', 'VOLUME ', 'VALUE '], axis = 1, inplace = True)
sp

OPEN    HIGH     LOW   PREV. CLOSE     ltp   close    vwap   \
0   367.70  371.90  363.10        364.30  370.95  370.65  367.07   
1   367.50  369.20  349.05        370.65  354.00  353.55  355.21   
2   355.70  357.00  349.30        353.55  350.95  350.55  353.10   
3   351.25  363.20  347.60        350.55  358.20  358.55  358.22   
4   361.00  363.30  354.30        358.55  355.95  355.60  358.65   
5   354.40  364.50  351.20        355.60  352.95  353.00  357.30   
6   344.00  344.00  322.55        353.00  330.70  328.85  329.89   
7   332.00  342.25  330.50        328.85  341.25  341.00  336.40   
8   342.10  347.55  336.10        341.00  342.55  342.70  341.70   
9   343.00  345.50  338.65        342.70  339.55  339.90  342.01   
10  327.15  332.05  321.30        339.90  330.45  331.15  326.36   
11  335.10  339.90  326.70        331.15  329.40  329.50  333.65   
12  326.00  337.65  323.30        329.50  336.25  336.65  332.72   
13  331.65  339.90  331.65        336.65  335.40  336.45  336.47   
14  339.25  347.45  339.25        336.45  344.80  344.30  345.26   
15  344.00  354.95  342.40        344.30  354.20  353.05  349.42   
16  357.00  364.30  356.05        353.05  362.90  363.40  361.63   
17  365.00  369.95  355.50        363.40  357.45  359.40  361.26   
18  353.45  362.50  350.45        359.40  352.30  353.50  357.11   
19  349.60  352.50  341.40        353.50  351.45  350.60  347.45   
20  355.00  362.90  350.20        350.60  351.10  351.50  357.53   
21  356.50  357.45  348.00        351.50  356.45  355.40  354.45   
22  358.00  359.35  350.55        355.40  355.85  355.55  354.51   
23  357.50  362.00  353.00        355.55  358.00  358.25  357.21   
24  360.50  367.00  358.80        358.25  362.30  361.70  362.87   
25  356.85  366.40  354.75        361.70  364.10  364.65  362.80   
26  362.80  373.50  361.90        364.65  367.75  367.70  368.18   
27  370.00  372.50  359.55        367.70  360.60  360.45  365.59   
28  364.40  385.20  363.65        360.45  384.45  383.10  376.90   
29  390.00  392.55  380.05        383.10  382.95  382.25  385.07   
30  382.00  389.50  381.20        382.25  384.40  384.40  385.63   
31  387.00  387.80  382.00        384.40  386.80  384.55  384.42   
32  390.00  404.40  378.00        384.55  404.00  401.20  393.52   
33  417.00  419.20  405.30        401.20  411.00  412.05  411.75   
34  415.10  415.50  408.50        412.05  414.10  412.35  411.05   
35  413.80  418.75  410.80        412.35  412.00  413.55  415.44   
36  413.70  429.10  412.00        413.55  426.80  425.20  419.80   
37  430.50  433.65  420.05        425.20  422.00  422.05  426.46   
38  421.00  426.00  418.00        422.05  424.50  424.35  422.90   

    No of trades   
0          201211  
1          382160  
2          273760  
3          323113  
4          221845  
5          303846  
6          579319  
7          319183  
8          325566  
9          237384  
10         396759  
11         248595  
12         279445  
13         272666  
14         306217  
15         293357  
16         337002  
17         348461  
18         296959  
19         313847  
20         342742  
21         244000  
22         217872  
23         224225  
24         260322  
25         229841  
26         320184  
27         358985  
28         654529  
29         483711  
30         346200  
31         331759  
32        1121959  
33         846514  
34         348160  
35         339506  
36         442431  
37         423239  
38         275082

# Splitting the data into x and y

In [137]:
y = sp['close ']
x = sp.drop('close ', axis  = 1)

In [138]:
# from sklearn.preprocessing import MinMaxScaler
# scaler = MinMaxScaler()
# x = scaler.fit_transform(x)

In [139]:
x = np.array(x)
# x

In [140]:
x = x[:,np.newaxis,:]

In [141]:
x

array([[[3.677000e+02, 3.719000e+02, 3.631000e+02, 3.643000e+02,
         3.709500e+02, 3.670700e+02, 2.012110e+05]],

       [[3.675000e+02, 3.692000e+02, 3.490500e+02, 3.706500e+02,
         3.540000e+02, 3.552100e+02, 3.821600e+05]],

       [[3.557000e+02, 3.570000e+02, 3.493000e+02, 3.535500e+02,
         3.509500e+02, 3.531000e+02, 2.737600e+05]],

       [[3.512500e+02, 3.632000e+02, 3.476000e+02, 3.505500e+02,
         3.582000e+02, 3.582200e+02, 3.231130e+05]],

       [[3.610000e+02, 3.633000e+02, 3.543000e+02, 3.585500e+02,
         3.559500e+02, 3.586500e+02, 2.218450e+05]],

       [[3.544000e+02, 3.645000e+02, 3.512000e+02, 3.556000e+02,
         3.529500e+02, 3.573000e+02, 3.038460e+05]],

       [[3.440000e+02, 3.440000e+02, 3.225500e+02, 3.530000e+02,
         3.307000e+02, 3.298900e+02, 5.793190e+05]],

       [[3.320000e+02, 3.422500e+02, 3.305000e+02, 3.288500e+02,
         3.412500e+02, 3.364000e+02, 3.191830e+05]],

       [[3.421000e+02, 3.475500e+02, 3.361000e+0

In [142]:
x.shape

(39, 1, 7)

In [143]:
np.random.seed(42)
tf.random.set_seed(42)
keras.backend.clear_session()
model = keras.models.Sequential([
    keras.layers.SimpleRNN(1, input_shape = [1,7])
])

In [144]:
optimizer = keras.optimizers.Adam(learning_rate= 0.005)
model.compile(loss = 'mse', optimizer = optimizer)

In [145]:
model.fit(x,y, validation_split = 0.2,epochs = 50 )

Epoch 1/50
1/1 [==============================] - 1s 901ms/step - loss: 124890.5078 - val_loss: 169011.6250
Epoch 2/50
1/1 [==============================] - 0s 44ms/step - loss: 124890.5156 - val_loss: 169011.6250
Epoch 3/50
1/1 [==============================] - 0s 55ms/step - loss: 124890.5156 - val_loss: 169011.6250
Epoch 4/50
1/1 [==============================] - 0s 56ms/step - loss: 124890.5156 - val_loss: 169011.6250
Epoch 5/50
1/1 [==============================] - 0s 54ms/step - loss: 124890.5156 - val_loss: 169011.6250
Epoch 6/50
1/1 [==============================] - 0s 55ms/step - loss: 124890.5078 - val_loss: 169011.6250
Epoch 7/50
1/1 [==============================] - 0s 53ms/step - loss: 124890.5156 - val_loss: 169011.6250
Epoch 8/50
1/1 [==============================] - 0s 64ms/step - loss: 124890.5078 - val_loss: 169011.6250
Epoch 9/50
1/1 [==============================] - 0s 56ms/step - loss: 124890.5078 - val_loss: 169011.6250
Epoch 10/50
1/1 [===================

In [146]:
model.predict([[[4.210000e+02, 4.260000e+02, 4.180000e+02, 4.220500e+02,
         4.245000e+02, 4.229000e+02, 2.750820e+05]]])

array([[1.]], dtype=float32)

In [119]:
test = np.arange(1,7).reshape(3,2)
test

array([[1, 2],
       [3, 4],
       [5, 6]])

In [120]:
test.ndim

2

In [121]:
test_1 = test[...,np.newaxis]
test_1

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])

In [122]:
test_2 = test[:,np.newaxis,:]
test_2

array([[[1, 2]],

       [[3, 4]],

       [[5, 6]]])

In [135]:
test_3 = test[np.newaxis,...]

In [136]:
test_3

array([[[1, 2],
        [3, 4],
        [5, 6]]])