In [1]:
import numpy as np

In [3]:
a = np.random.rand(5,3)

In [4]:
a

array([[0.07101684, 0.01423201, 0.45824144],
       [0.51913463, 0.40126154, 0.85582864],
       [0.13198479, 0.03479927, 0.04064292],
       [0.58444603, 0.25774933, 0.55107449],
       [0.40419922, 0.9275516 , 0.70005936]])

In [36]:
b = np.random.rand(5,2)

In [37]:
b

array([[0.11065487, 0.98511392],
       [0.35870616, 0.93535598],
       [0.51590582, 0.443149  ],
       [0.91311936, 0.01842798],
       [0.96984895, 0.4969263 ]])

In [38]:
c = np.concatenate((a,b), axis = 1)
c

array([[0.07101684, 0.01423201, 0.45824144, 0.11065487, 0.98511392],
       [0.51913463, 0.40126154, 0.85582864, 0.35870616, 0.93535598],
       [0.13198479, 0.03479927, 0.04064292, 0.51590582, 0.443149  ],
       [0.58444603, 0.25774933, 0.55107449, 0.91311936, 0.01842798],
       [0.40419922, 0.9275516 , 0.70005936, 0.96984895, 0.4969263 ]])

In [25]:
np.c_?

Type:        CClass
String form: <numpy.lib.index_tricks.CClass object at 0x7ff9c5160370>
Length:      0
File:        /usr/lib/python3.9/site-packages/numpy/lib/index_tricks.py
Docstring:  
Translates slice objects to concatenation along the second axis.

This is short-hand for ``np.r_['-1,2,0', index expression]``, which is
useful because of its common occurrence. In particular, arrays will be
stacked along their last axis after being upgraded to at least 2-D with
1's post-pended to the shape (column vectors made out of 1-D arrays).

See Also
--------
column_stack : Stack 1-D arrays as columns into a 2-D array.
r_ : For more detailed documentation.

Examples
--------
>>> np.c_[np.array([1,2,3]), np.array([4,5,6])]
array([[1, 4],
       [2, 5],
       [3, 6]])
>>> np.c_[np.array([[1,2,3]]), 0, 0, np.array([[4,5,6]])]
array([[1, 2, 3, ..., 4, 5, 6]])


In [26]:
np.c_[np.array([[1,2,3]]), 0, 0, np.array([[4,5,6]])]

array([[1, 2, 3, 0, 0, 4, 5, 6]])

In [27]:
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [33]:
d =  np.random.rand(5,2)
d

array([[0.30931447, 0.6354044 ],
       [0.07970525, 0.91996311],
       [0.67899783, 0.7951942 ],
       [0.72657029, 0.7246999 ],
       [0.11635615, 0.58712532]])

In [34]:
np.c_[a,d]

array([[0.07101684, 0.01423201, 0.45824144, 0.30931447, 0.6354044 ],
       [0.51913463, 0.40126154, 0.85582864, 0.07970525, 0.91996311],
       [0.13198479, 0.03479927, 0.04064292, 0.67899783, 0.7951942 ],
       [0.58444603, 0.25774933, 0.55107449, 0.72657029, 0.7246999 ],
       [0.40419922, 0.9275516 , 0.70005936, 0.11635615, 0.58712532]])

In [42]:
import pandas as pd
pd.set_option('display.max_columns', 30)

In [44]:
cp = pd.read_csv('/home/athharv/Downloads/car_price.csv')
cp.head()

symboling normalized_losses Fuel_type make num_of_doors   aspiration  \
0          3                 ?       gas  std          two  convertible   
1          3                 ?       gas  std          two  convertible   
2          1                 ?       gas  std          two    hatchback   
3          2               164       gas  std         four        sedan   
4          2               164       gas  std         four        sedan   

  wheel_base engine_location  drive_wheels   body_style  length  width  \
0        rwd           front          88.6  alfa-romero   168.8   64.1   
1        rwd           front          88.6  alfa-romero   168.8   64.1   
2        rwd           front          94.5  alfa-romero   171.2   65.5   
3        fwd           front          99.8         audi   176.6   66.2   
4        4wd           front          99.4         audi   176.6   66.4   

   height  curb_weight engine_type num_of_cylinders  engine_size fuel_system  \
0    48.8         2548        dohc             four          130        mpfi   
1    48.8         2548        dohc             four          130        mpfi   
2    52.4         2823        ohcv              six          152        mpfi   
3    54.3         2337         ohc             four          109        mpfi   
4    54.3         2824         ohc             five          136        mpfi   

   bore stroke  compression_ratio horsepower peak_rpm  city_mpg  highway_mpg  \
0  3.47   2.68                9.0        111     5000        21           27   
1  3.47   2.68                9.0        111     5000        21           27   
2  2.68   3.47                9.0        154     5000        19           26   
3  3.19    3.4               10.0        102     5500        24           30   
4  3.19    3.4                8.0        115     5500        18           22   

   price  
0  13495  
1  16500  
2  16500  
3  13950  
4  17450

In [50]:
cp[['symboling','Fuel_type']]

symboling Fuel_type
0            3       gas
1            3       gas
2            1       gas
3            2       gas
4            2       gas
..         ...       ...
200         -1       gas
201         -1       gas
202         -1       gas
203         -1    diesel
204         -1       gas

[205 rows x 2 columns]

In [48]:
cp.symboling

0      3
1      3
2      1
3      2
4      2
      ..
200   -1
201   -1
202   -1
203   -1
204   -1
Name: symboling, Length: 205, dtype: int64

In [56]:
cp[list(cp.columns[:5])]

symboling normalized_losses Fuel_type   make num_of_doors
0            3                 ?       gas    std          two
1            3                 ?       gas    std          two
2            1                 ?       gas    std          two
3            2               164       gas    std         four
4            2               164       gas    std         four
..         ...               ...       ...    ...          ...
200         -1                95       gas    std         four
201         -1                95       gas  turbo         four
202         -1                95       gas    std         four
203         -1                95    diesel  turbo         four
204         -1                95       gas  turbo         four

[205 rows x 5 columns]

In [62]:
cp.select_dtypes(include = 'float')

drive_wheels  length  width  height  compression_ratio
0            88.6   168.8   64.1    48.8                9.0
1            88.6   168.8   64.1    48.8                9.0
2            94.5   171.2   65.5    52.4                9.0
3            99.8   176.6   66.2    54.3               10.0
4            99.4   176.6   66.4    54.3                8.0
..            ...     ...    ...     ...                ...
200         109.1   188.8   68.9    55.5                9.5
201         109.1   188.8   68.8    55.5                8.7
202         109.1   188.8   68.9    55.5                8.8
203         109.1   188.8   68.9    55.5               23.0
204         109.1   188.8   68.9    55.5                9.5

[205 rows x 5 columns]

In [67]:
cp.iloc[2:3,:]

symboling normalized_losses Fuel_type make num_of_doors aspiration  \
2          1                 ?       gas  std          two  hatchback   

  wheel_base engine_location  drive_wheels   body_style  length  width  \
2        rwd           front          94.5  alfa-romero   171.2   65.5   

   height  curb_weight engine_type num_of_cylinders  engine_size fuel_system  \
2    52.4         2823        ohcv              six          152        mpfi   

   bore stroke  compression_ratio horsepower peak_rpm  city_mpg  highway_mpg  \
2  2.68   3.47                9.0        154     5000        19           26   

   price  
2  16500