In [1]:
import numpy as np

In [14]:
a = np.arange(6).reshape(1,6)
a

array([[0, 1, 2, 3, 4, 5]])

In [15]:
b = np.array([[10],[20],[30],[40],[50],[60]])
b

array([[10],
       [20],
       [30],
       [40],
       [50],
       [60]])

In [16]:
c = a+b
c.shape

(6, 6)

In [17]:
c

array([[10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55],
       [60, 61, 62, 63, 64, 65]])

In [22]:
z = np.arange(1,25).reshape(3,2,4)
z

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [28]:
z+[[100],[200]]

array([[[101, 102, 103, 104],
        [205, 206, 207, 208]],

       [[109, 110, 111, 112],
        [213, 214, 215, 216]],

       [[117, 118, 119, 120],
        [221, 222, 223, 224]]])

In [30]:
z.min()

1

In [31]:
z.max()

24

In [32]:
z.mean()

12.5

In [33]:
z.prod()

-7835185981329244160

In [35]:
z.sum()

300

In [36]:
z.std()

6.922186552431729

In [37]:
z.var()

47.916666666666664

In [38]:
z

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [41]:
z = z.reshape(6,4)
z

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [42]:
z.sum(axis = 0)

array([66, 72, 78, 84])

In [43]:
z.sum(axis =1)

array([10, 26, 42, 58, 74, 90])

In [44]:
# Solving system of linear equations with numpy

# 2x + 3y = 16
# x  + 2y = 10

coef = np.array([[2,3],[1,2]])
dep = np.array([16,10])

In [45]:
sol = np.linalg.solve(coef,dep)
sol

array([2., 4.])

In [47]:
coef.dot(sol)

array([16., 10.])

In [48]:
a = np.arange(10)
b = a*a
b

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [49]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.c_[a,b]

array([[ 0,  0],
       [ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16],
       [ 5, 25],
       [ 6, 36],
       [ 7, 49],
       [ 8, 64],
       [ 9, 81]])