In [2]:
import numpy as np

In [11]:
arr = np.array([x for x in range(1,26)]).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [12]:
arr[0,1]

2

In [13]:
arr[1:3,1:3]

array([[ 7,  8],
       [12, 13]])

In [15]:
arr[1:4,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [18]:
 y = arr[2:,2:5]
 y

array([[13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [19]:
y[0,0] = 200

In [20]:
arr

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12, 200,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25]])

In [34]:
y = np.array([100,200,300,400,500,600,700,800,900,1000]).reshape(2,5)

In [35]:
z = np.c_[arr,y]

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 5 and the array at index 1 has size 2

In [36]:
z

array([[   1,    2,    3,    4,    5,  100,  200],
       [   6,    7,    8,    9,   10,  300,  400],
       [  11,   12,  200,   14,   15,  500,  600],
       [  16,   17,   18,   19,   20,  700,  800],
       [  21,   22,   23,   24,   25,  900, 1000]])

In [38]:
z_ = np.concatenate([arr,y],axis = 0)

In [40]:
z_

array([[   1,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10],
       [  11,   12,  200,   14,   15],
       [  16,   17,   18,   19,   20],
       [  21,   22,   23,   24,   25],
       [ 100,  200,  300,  400,  500],
       [ 600,  700,  800,  900, 1000]])

In [44]:
zer = np.zeros((3,5), dtype = 'int64')
zer

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [45]:
one = np.ones((5,3))
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [49]:
cust = np.full((4,3),300, dtype = np.int64)
cust

array([[300, 300, 300],
       [300, 300, 300],
       [300, 300, 300],
       [300, 300, 300]])

In [55]:
a = np.arange(4,10,3,dtype = np.int64)
a

array([4, 7])

In [52]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use `numpy.linspace` for these cases.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : integer or real
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : integer or real, optional
    Spacing between values.  For any output `out`, this is the distance
  