In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Importing Iris dataset

In [41]:
from sklearn import datasets
iris = datasets.load_iris()
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [52]:
x = iris['data'][:,(2,3)]       # petal length (cm)','petal width (cm)'
y = (iris['target'] == 2).astype(np.float64)       # Iris verginica

In [53]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC 

In [54]:
scaler = StandardScaler()
svc_clf = LinearSVC(C = 1, loss = 'hinge')
svc_clf_scaled = Pipeline([('scaler', scaler),('classifier', svc_clf)])

In [55]:
from sklearn.impute import SimpleImputer

In [56]:
simple_imputer = SimpleImputer(strategy='median')

In [59]:
y_ = np.array([1,2,3,np.nan,10,-2,-9]).reshape(-1,1)
y_

array([[ 1.],
       [ 2.],
       [ 3.],
       [nan],
       [10.],
       [-2.],
       [-9.]])

In [62]:
y_ravel = y_.ravel()
y_ravel

array([ 1.,  2.,  3., nan, 10., -2., -9.])

In [38]:
y_filled = simple_imputer.fit_transform(y_)

In [39]:
y_filled

array([[ 1. ],
       [ 2. ],
       [ 3. ],
       [ 1.5],
       [10. ],
       [-2. ],
       [-9. ]])

In [45]:
svc_clf.fit(x,y)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


LinearSVC(C=1, loss='hinge')

In [57]:
svc_clf_scaled.fit(x,y)

Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier', LinearSVC(C=1, loss='hinge'))])

In [58]:
svc_clf_scaled.predict([[3.5,2]])

array([0.])