In [1]:
import numpy as np

In [19]:
x = np.ones((3,3,3,2))

In [20]:
x

array([[[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]]])

In [23]:
m = np.full((2,3), 3.72)

In [24]:
m

array([[3.72, 3.72, 3.72],
       [3.72, 3.72, 3.72]])

In [27]:
rang = np.arange(10.2,31,4)

In [30]:
rang

array([10.2, 14.2, 18.2, 22.2, 26.2, 30.2])

In [32]:
linear = np.linspace(10.2,31,10)
linear

array([10.2       , 12.51111111, 14.82222222, 17.13333333, 19.44444444,
       21.75555556, 24.06666667, 26.37777778, 28.68888889, 31.        ])

In [33]:
12.51111111 - 10.2

2.3111111100000006

In [35]:
14.82222222- 12.51111111

2.3111111100000006

In [38]:
rand_num = np.random.rand(3,4)
rand_num

array([[0.80630671, 0.56259927, 0.89257171, 0.37634961],
       [0.54725916, 0.24401144, 0.08290296, 0.60440937],
       [0.9941865 , 0.19983704, 0.52240212, 0.83047947]])

In [40]:
empty = np.empty((3,4))
empty

array([[0.04248142, 0.50890164, 0.75634183, 0.84139644],
       [0.30989255, 0.63765581, 0.61606344, 0.52972423],
       [0.50201235, 0.27284794, 0.69808923, 0.08743669]])

In [41]:
empty.ndim

2

In [42]:
x.ndim

4

In [43]:
x.shape

(3, 3, 3, 2)

In [44]:
empty.shape

(3, 4)

In [45]:
x.size

54

In [46]:
empty.size

12

In [47]:
empty.itemsize

8

In [51]:
t = np.arange(10,20,0.5)
t.shape

(20,)

In [53]:
v = t.reshape(4,5)

In [58]:
v.shape

(10, 2)

In [57]:
v = v.reshape(10,2)

In [69]:
v = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
v

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [77]:
v[1:,2:] = -4
v

array([[ 1,  2,  3,  4],
       [ 5,  6, -4, -4],
       [ 9, 10, -4, -4]])

In [70]:
v[1]            # row complete

array([5, 6, 7, 8])

In [71]:
v[:,3]

array([ 4,  8, 12])

In [73]:
v[2,2]

11

In [75]:
v[1:,2]

array([ 7, 11])