In [32]:
import numpy as np
np.random.seed(42)

In [6]:
l = [1,2,3,4,5,6,3.2,5]
l_a = np.array(l,dtype = np.float16)
l_a

array([1. , 2. , 3. , 4. , 5. , 6. , 3.2, 5. ], dtype=float16)

In [7]:
l_a.dtype

dtype('float16')

In [49]:
a = np.empty((2,5,3,3))

In [50]:
a

array([[[[4.64358585e-310, 0.00000000e+000, 6.91532068e-310],
         [6.91532068e-310, 6.91532068e-310, 6.91532068e-310],
         [6.91532068e-310, 6.91532068e-310, 6.91532068e-310]],

        [[6.91532068e-310, 6.91532068e-310, 6.91532068e-310],
         [6.91532068e-310, 6.91532068e-310, 6.91532068e-310],
         [6.91532068e-310, 6.91532068e-310, 6.91532068e-310]],

        [[6.91532068e-310, 6.91532068e-310, 6.91532068e-310],
         [6.91532068e-310, 6.91532068e-310, 6.91532068e-310],
         [6.91532068e-310, 6.91532068e-310, 6.91532068e-310]],

        [[6.91532068e-310, 6.91532068e-310, 6.91532068e-310],
         [6.91532068e-310, 6.91532068e-310, 6.91532068e-310],
         [6.91532068e-310, 6.91532068e-310, 6.91532068e-310]],

        [[6.91532068e-310, 6.91532068e-310, 6.91532068e-310],
         [6.91532067e-310, 6.91532051e-310, 6.91532066e-310],
         [6.91532036e-310, 6.91532041e-310, 6.91532041e-310]]],


       [[[6.91532048e-310, 6.91532068e-310, 6.91532084e-31

In [20]:
np.zeros((3,5), dtype = np.int8)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

In [21]:
np.full((3,4),0.6)

array([[0.6, 0.6, 0.6, 0.6],
       [0.6, 0.6, 0.6, 0.6],
       [0.6, 0.6, 0.6, 0.6]])

In [23]:
np.arange(0,5,2)

array([0, 2, 4])

In [24]:
np.linspace(2,10,100)

array([ 2.        ,  2.08080808,  2.16161616,  2.24242424,  2.32323232,
        2.4040404 ,  2.48484848,  2.56565657,  2.64646465,  2.72727273,
        2.80808081,  2.88888889,  2.96969697,  3.05050505,  3.13131313,
        3.21212121,  3.29292929,  3.37373737,  3.45454545,  3.53535354,
        3.61616162,  3.6969697 ,  3.77777778,  3.85858586,  3.93939394,
        4.02020202,  4.1010101 ,  4.18181818,  4.26262626,  4.34343434,
        4.42424242,  4.50505051,  4.58585859,  4.66666667,  4.74747475,
        4.82828283,  4.90909091,  4.98989899,  5.07070707,  5.15151515,
        5.23232323,  5.31313131,  5.39393939,  5.47474747,  5.55555556,
        5.63636364,  5.71717172,  5.7979798 ,  5.87878788,  5.95959596,
        6.04040404,  6.12121212,  6.2020202 ,  6.28282828,  6.36363636,
        6.44444444,  6.52525253,  6.60606061,  6.68686869,  6.76767677,
        6.84848485,  6.92929293,  7.01010101,  7.09090909,  7.17171717,
        7.25252525,  7.33333333,  7.41414141,  7.49494949,  7.57

In [42]:
np.random.seed(42)
np.random.rand(2,5)

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258]])

In [51]:
a.ndim

4