In [4]:
import time
import numpy as np

In [5]:
def multiply_loops(A, B):
    C = np.zeros((A.shape[0], B.shape[1]))
    for i in range(A.shape[1]):
        for j in range(B.shape[0]):
            C[i, j] = A[i, j] * B[j, i]
    return C

In [19]:
a = np.random.randn(1000,1000)
b = np.random.randn(1000,1000)
start =time.time()
time.sleep(1)
x = multiply_loops(a,b)
print(f'time taken is {time.time()-start}')

time taken is 1.5387649536132812


In [20]:
def multiply_vector(A, B):
    return A @ B

In [21]:
start =time.time()
time.sleep(1)
multiply_vector(a,b)
print(f'time taken is {time.time()-start}')

time taken is 1.0577950477600098


In [22]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[1,2],
              [3,4]])
a*b

array([[ 1,  4],
       [ 9, 16]])

In [23]:
a.dot(b)

array([[ 7, 10],
       [15, 22]])

In [27]:
m = np.array([20, -5, 30, 40])
m < [15, 16, 35, 36]

array([False,  True,  True, False])

In [29]:
n = m[m<25]
n

array([20, -5])

In [38]:
coeffs = np.array([[2, 6, 3], 
                   [5, 3, 10],
                   [2, 10, 5]])
vars = np.array([5, -19, -3])

solution = np.linalg.solve(coeffs, vars)
solution

array([ 8.5       ,  1.26470588, -6.52941176])

In [39]:
coeffs.dot(solution)

array([  5., -19.,  -3.])