In [1]:
import numpy as np

In [2]:
a = np.random.rand(5,3)

In [3]:
a

array([[0.83770083, 0.76346513, 0.88548083],
       [0.83723778, 0.48224226, 0.56537928],
       [0.398396  , 0.63587034, 0.83804826],
       [0.3403531 , 0.90021452, 0.42478363],
       [0.25808261, 0.72103842, 0.98647568]])

In [4]:
b = np.random.rand(5,2)

In [5]:
b

array([[0.04573044, 0.99029958],
       [0.44623983, 0.12298667],
       [0.52028107, 0.52630318],
       [0.45795665, 0.51411241],
       [0.21533061, 0.14941331]])

In [6]:
c = np.concatenate((a,b), axis = 1)
c

array([[0.83770083, 0.76346513, 0.88548083, 0.04573044, 0.99029958],
       [0.83723778, 0.48224226, 0.56537928, 0.44623983, 0.12298667],
       [0.398396  , 0.63587034, 0.83804826, 0.52028107, 0.52630318],
       [0.3403531 , 0.90021452, 0.42478363, 0.45795665, 0.51411241],
       [0.25808261, 0.72103842, 0.98647568, 0.21533061, 0.14941331]])

In [7]:
np.c_?

Type:        CClass
String form: <numpy.lib.index_tricks.CClass object at 0x7f095db9f790>
Length:      0
File:        /usr/lib/python3.9/site-packages/numpy/lib/index_tricks.py
Docstring:  
Translates slice objects to concatenation along the second axis.

This is short-hand for ``np.r_['-1,2,0', index expression]``, which is
useful because of its common occurrence. In particular, arrays will be
stacked along their last axis after being upgraded to at least 2-D with
1's post-pended to the shape (column vectors made out of 1-D arrays).

See Also
--------
column_stack : Stack 1-D arrays as columns into a 2-D array.
r_ : For more detailed documentation.

Examples
--------
>>> np.c_[np.array([1,2,3]), np.array([4,5,6])]
array([[1, 4],
       [2, 5],
       [3, 6]])
>>> np.c_[np.array([[1,2,3]]), 0, 0, np.array([[4,5,6]])]
array([[1, 2, 3, ..., 4, 5, 6]])


In [8]:
np.c_[np.array([[1,2,3]]), 0, 0, np.array([[4,5,6]])]

array([[1, 2, 3, 0, 0, 4, 5, 6]])

In [9]:
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [10]:
d =  np.random.rand(5,2)
d

array([[0.67983491, 0.714379  ],
       [0.91659875, 0.13599176],
       [0.67186497, 0.67018328],
       [0.09784462, 0.00962614],
       [0.53554431, 0.98214329]])

In [11]:
np.c_[a,d]

array([[0.83770083, 0.76346513, 0.88548083, 0.67983491, 0.714379  ],
       [0.83723778, 0.48224226, 0.56537928, 0.91659875, 0.13599176],
       [0.398396  , 0.63587034, 0.83804826, 0.67186497, 0.67018328],
       [0.3403531 , 0.90021452, 0.42478363, 0.09784462, 0.00962614],
       [0.25808261, 0.72103842, 0.98647568, 0.53554431, 0.98214329]])

In [12]:
import pandas as pd
pd.set_option('display.max_columns', 30)

In [13]:
cp = pd.read_csv('/home/athharv/Downloads/car_price.csv')
cp.head()

symboling normalized_losses Fuel_type make num_of_doors   aspiration  \
0          3                 ?       gas  std          two  convertible   
1          3                 ?       gas  std          two  convertible   
2          1                 ?       gas  std          two    hatchback   
3          2               164       gas  std         four        sedan   
4          2               164       gas  std         four        sedan   

  wheel_base engine_location  drive_wheels   body_style  length  width  \
0        rwd           front          88.6  alfa-romero   168.8   64.1   
1        rwd           front          88.6  alfa-romero   168.8   64.1   
2        rwd           front          94.5  alfa-romero   171.2   65.5   
3        fwd           front          99.8         audi   176.6   66.2   
4        4wd           front          99.4         audi   176.6   66.4   

   height  curb_weight engine_type num_of_cylinders  engine_size fuel_system  \
0    48.8         2548        dohc             four          130        mpfi   
1    48.8         2548        dohc             four          130        mpfi   
2    52.4         2823        ohcv              six          152        mpfi   
3    54.3         2337         ohc             four          109        mpfi   
4    54.3         2824         ohc             five          136        mpfi   

   bore stroke  compression_ratio horsepower peak_rpm  city_mpg  highway_mpg  \
0  3.47   2.68                9.0        111     5000        21           27   
1  3.47   2.68                9.0        111     5000        21           27   
2  2.68   3.47                9.0        154     5000        19           26   
3  3.19    3.4               10.0        102     5500        24           30   
4  3.19    3.4                8.0        115     5500        18           22   

   price  
0  13495  
1  16500  
2  16500  
3  13950  
4  17450

In [14]:
cp[['symboling','Fuel_type']]

symboling Fuel_type
0            3       gas
1            3       gas
2            1       gas
3            2       gas
4            2       gas
..         ...       ...
200         -1       gas
201         -1       gas
202         -1       gas
203         -1    diesel
204         -1       gas

[205 rows x 2 columns]

In [15]:
cp.symboling

0      3
1      3
2      1
3      2
4      2
      ..
200   -1
201   -1
202   -1
203   -1
204   -1
Name: symboling, Length: 205, dtype: int64

In [16]:
cp[list(cp.columns[:5])]

symboling normalized_losses Fuel_type   make num_of_doors
0            3                 ?       gas    std          two
1            3                 ?       gas    std          two
2            1                 ?       gas    std          two
3            2               164       gas    std         four
4            2               164       gas    std         four
..         ...               ...       ...    ...          ...
200         -1                95       gas    std         four
201         -1                95       gas  turbo         four
202         -1                95       gas    std         four
203         -1                95    diesel  turbo         four
204         -1                95       gas  turbo         four

[205 rows x 5 columns]

In [17]:
cp.select_dtypes(include = 'float')

drive_wheels  length  width  height  compression_ratio
0            88.6   168.8   64.1    48.8                9.0
1            88.6   168.8   64.1    48.8                9.0
2            94.5   171.2   65.5    52.4                9.0
3            99.8   176.6   66.2    54.3               10.0
4            99.4   176.6   66.4    54.3                8.0
..            ...     ...    ...     ...                ...
200         109.1   188.8   68.9    55.5                9.5
201         109.1   188.8   68.8    55.5                8.7
202         109.1   188.8   68.9    55.5                8.8
203         109.1   188.8   68.9    55.5               23.0
204         109.1   188.8   68.9    55.5                9.5

[205 rows x 5 columns]

In [32]:
cp.iloc[1:3,0:5]

symboling normalized_losses Fuel_type make num_of_doors
0          3                 ?       gas  std          two
1          3                 ?       gas  std          two
2          1                 ?       gas  std          two
3          2               164       gas  std         four

In [42]:
cp.loc[:4,list(cp.columns)[0:5]]

symboling normalized_losses Fuel_type make num_of_doors
0         3                 ?       gas  std          two
1         3                 ?       gas  std          two
2         1                 ?       gas  std          two
3         2               164       gas  std         four
4         2               164       gas  std         four

In [41]:
cp.iloc[0:2,0] = 3

In [37]:
cp.loc[0:1,['symboling','normalized_losses']] = 4

In [44]:
arr = np.array(cp.loc[:4,list(cp.columns)[0:5]])
arr

array([[3, '?', 'gas', 'std', 'two'],
       [3, '?', 'gas', 'std', 'two'],
       [1, '?', 'gas', 'std', 'two'],
       [2, '164', 'gas', 'std', 'four'],
       [2, '164', 'gas', 'std', 'four']], dtype=object)

In [47]:
arr[0:2,[0,1,3]]

array([[3, '?', 'std'],
       [3, '?', 'std']], dtype=object)

In [48]:
cp.iloc[0:2,[0,1,3]]

symboling normalized_losses make
0         3                 ?  std
1         3                 ?  std