In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5,6]
print(l)
l = np.array(l,dtype = np.int8)
l

[1, 2, 3, 4, 5, 6]


array([1, 2, 3, 4, 5, 6], dtype=int8)

In [3]:
l.dtype

dtype('int8')

In [4]:
l1 = [1,2,3,4,5.5,6]
l1 = np.array(l1)
l1

array([1. , 2. , 3. , 4. , 5.5, 6. ])

In [5]:
l2 = [1,2,3,'4',5.5,6]
l2 = np.array(l2)
l2

array(['1', '2', '3', '4', '5.5', '6'], dtype='<U32')

In [6]:
l3 = np.arange(1,11,2)
l3

array([1, 3, 5, 7, 9])

In [7]:
l3 = np.linspace(1,5,20)
l3

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [8]:
l4 = np.random.rand(3,5)
l4

array([[0.16127658, 0.05100833, 0.79063639, 0.27367555, 0.44131291],
       [0.98761158, 0.98003142, 0.26288793, 0.14514269, 0.25110413],
       [0.54969472, 0.27783331, 0.72207896, 0.75939115, 0.42171141]])

In [9]:
l5 = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
l5 = np.array(l5)
l5

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
l5.shape

(4, 3)

In [11]:
l5.ndim

2

In [12]:
d_arr = np.full((3,2,4,5),3.2)
d_arr

array([[[[3.2, 3.2, 3.2, 3.2, 3.2],
         [3.2, 3.2, 3.2, 3.2, 3.2],
         [3.2, 3.2, 3.2, 3.2, 3.2],
         [3.2, 3.2, 3.2, 3.2, 3.2]],

        [[3.2, 3.2, 3.2, 3.2, 3.2],
         [3.2, 3.2, 3.2, 3.2, 3.2],
         [3.2, 3.2, 3.2, 3.2, 3.2],
         [3.2, 3.2, 3.2, 3.2, 3.2]]],


       [[[3.2, 3.2, 3.2, 3.2, 3.2],
         [3.2, 3.2, 3.2, 3.2, 3.2],
         [3.2, 3.2, 3.2, 3.2, 3.2],
         [3.2, 3.2, 3.2, 3.2, 3.2]],

        [[3.2, 3.2, 3.2, 3.2, 3.2],
         [3.2, 3.2, 3.2, 3.2, 3.2],
         [3.2, 3.2, 3.2, 3.2, 3.2],
         [3.2, 3.2, 3.2, 3.2, 3.2]]],


       [[[3.2, 3.2, 3.2, 3.2, 3.2],
         [3.2, 3.2, 3.2, 3.2, 3.2],
         [3.2, 3.2, 3.2, 3.2, 3.2],
         [3.2, 3.2, 3.2, 3.2, 3.2]],

        [[3.2, 3.2, 3.2, 3.2, 3.2],
         [3.2, 3.2, 3.2, 3.2, 3.2],
         [3.2, 3.2, 3.2, 3.2, 3.2],
         [3.2, 3.2, 3.2, 3.2, 3.2]]]])

In [13]:
d_arr.ndim

4

In [14]:
mat = np.linspace(20,50,24).reshape(3,4,2)
mat

array([[[20.        , 21.30434783],
        [22.60869565, 23.91304348],
        [25.2173913 , 26.52173913],
        [27.82608696, 29.13043478]],

       [[30.43478261, 31.73913043],
        [33.04347826, 34.34782609],
        [35.65217391, 36.95652174],
        [38.26086957, 39.56521739]],

       [[40.86956522, 42.17391304],
        [43.47826087, 44.7826087 ],
        [46.08695652, 47.39130435],
        [48.69565217, 50.        ]]])

In [23]:
m1 = np.array([[1,2,3],[1,2,3],[1,2,3]])
m1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [24]:
m2 = np.array([[1,2,3],[1,2,3],[1,2,3]])
m2

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [25]:
m1.dot(m2)

array([[ 6, 12, 18],
       [ 6, 12, 18],
       [ 6, 12, 18]])

In [26]:
m2@m1

array([[ 6, 12, 18],
       [ 6, 12, 18],
       [ 6, 12, 18]])

In [35]:
'''
2*x + 3*y = 15
7*x + 4*y= 10
'''

'\n2*x + 3*y = 15\n7*x + 4*y= 10\n'

In [29]:
indep = [[2,3],[7,4]]
dep = [15,10]

In [32]:
sol = np.linalg.solve(indep,dep)
sol

array([-2.30769231,  6.53846154])

In [34]:
np.array(indep).dot(sol)

array([15., 10.])

In [2]:
import pandas as pd

In [20]:
fitness = pd.read_csv(r'/mnt/New_Volume/Work_From_Home/Data/CardioGoodFitness.csv')
fitness.head()

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  Miles
0   TM195   18    Male         14        Single      3        4   29562    112
1   TM195   19    Male         15        Single      2        3   31836     75
2   TM195   19  Female         14     Partnered      4        3   30699     66
3   TM195   19    Male         12        Single      3        3   32973     85
4   TM195   20    Male         13     Partnered      4        2   35247     47

In [4]:
fitness['Product']

0      TM195
1      TM195
2      TM195
3      TM195
4      TM195
       ...  
175    TM798
176    TM798
177    TM798
178    TM798
179    TM798
Name: Product, Length: 180, dtype: object

In [5]:
fitness.Product

0      TM195
1      TM195
2      TM195
3      TM195
4      TM195
       ...  
175    TM798
176    TM798
177    TM798
178    TM798
179    TM798
Name: Product, Length: 180, dtype: object

In [6]:
fitness[["Product",'Usage','Gender']]

Product  Usage  Gender
0     TM195      3    Male
1     TM195      2    Male
2     TM195      4  Female
3     TM195      3    Male
4     TM195      4    Male
..      ...    ...     ...
175   TM798      6    Male
176   TM798      5    Male
177   TM798      5    Male
178   TM798      4    Male
179   TM798      4    Male

[180 rows x 3 columns]

In [7]:
fitness.loc[[0,1,2,3,4,6,8,10],['Product', 'Gender', 'Age']]

Product  Gender  Age
0    TM195    Male   18
1    TM195    Male   19
2    TM195  Female   19
3    TM195    Male   19
4    TM195    Male   20
6    TM195  Female   21
8    TM195    Male   21
10   TM195    Male   22

In [8]:
fitness.Product[0]

'TM195'

In [9]:
fitness.loc[0:11,['Product', 'Gender', 'Age']]

Product  Gender  Age
0    TM195    Male   18
1    TM195    Male   19
2    TM195  Female   19
3    TM195    Male   19
4    TM195    Male   20
5    TM195  Female   20
6    TM195  Female   21
7    TM195    Male   21
8    TM195    Male   21
9    TM195  Female   21
10   TM195    Male   22
11   TM195  Female   22

In [10]:
fitness.iloc[0:11,[0,2,1]]

Product  Gender  Age
0    TM195    Male   18
1    TM195    Male   19
2    TM195  Female   19
3    TM195    Male   19
4    TM195    Male   20
5    TM195  Female   20
6    TM195  Female   21
7    TM195    Male   21
8    TM195    Male   21
9    TM195  Female   21
10   TM195    Male   22

In [11]:
fitness.columns = ['Product', 'agee', 'Gender', 'Education', 'MaritalStatus', 'Usage','Fitness', 'Income', 'Miles']

In [21]:
fitness.rename({'Product':'productt'}, inplace = True, axis = 1)

In [25]:
fitness['productt'].name

'Prroductt'

In [28]:
fitness['productt'].name = 'Prroductt'
fitness['productt'] = pd.Series({fitness['productt'].name: fitness['productt']})

In [29]:
fitness

productt  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  \
0        NaN   18    Male         14        Single      3        4   29562   
1        NaN   19    Male         15        Single      2        3   31836   
2        NaN   19  Female         14     Partnered      4        3   30699   
3        NaN   19    Male         12        Single      3        3   32973   
4        NaN   20    Male         13     Partnered      4        2   35247   
..       ...  ...     ...        ...           ...    ...      ...     ...   
175      NaN   40    Male         21        Single      6        5   83416   
176      NaN   42    Male         18        Single      5        4   89641   
177      NaN   45    Male         16        Single      5        5   90886   
178      NaN   47    Male         18     Partnered      4        5  104581   
179      NaN   48    Male         18     Partnered      4        5   95508   

     Miles  
0      112  
1       75  
2       66  
3       85  
4       47  
..     ...  
175    200  
176    200  
177    160  
178    120  
179    180  

[180 rows x 9 columns]

In [122]:
fitness.head()

Product  agee  Gender  Education MaritalStatus  Usage  Fitness  Income  \
0   TM195    18    Male         14        Single      3        4   29562   
1   TM195    19    Male         15        Single      2        3   31836   
2   TM195    19  Female         14     Partnered      4        3   30699   
3   TM195    19    Male         12        Single      3        3   32973   
4   TM195    20    Male         13     Partnered      4        2   35247   

   Miles  
0    112  
1     75  
2     66  
3     85  
4     47